version: "3.0"
services:
  postgres:
    env_file:
      - ./.env.example
    image: postgres:13
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '127.0.0.1:5432:5432'
  core-api:
    env_file:
      - ./.env.example
    build:
      context: .
    command: uvicorn cores_app.main:app --host 0.0.0.0 --port 80 --reload
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DEBUG=yes

    ports:
      - "8000:80"
    depends_on:
      - postgres
    tty: true
    volumes:
      - .:/code/:Z
